@host = localhost:8080

// Register User
POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{
    "name": "Mukesh Murugan",
    "username": "mukesh.murugan",
    "email": "mukesh@go.com",
    "password": "123465789"
}

###